### ISSUE TITLE
Missing PSVita inputs

### ISSUE THREAD

**Issue by Ch0wW** [Rinnegatamante/vitaQuake#11]
Whenever you start a new game for the first time, everything works flawlessly.
However, if you try another time to start a new game, it gives the following message:

> Are you sure to start a new game?

No button can be pressed, meaning all you can do is to restart vitaQuake.

EDIT: Also reported by Hoshi:

> <Hoshi> danzeff keyboard doesnt startup when you want to change a nick

**Comment by Ch0wW** [comment]
This commit fixes most menu inputs, and removed the "are you sure you want to start a new game" check aswell as bringing a lot more rewritings (pull request incoming).

https://github.com/Ch0wW/vitaQuake/commit/aaac33e7130906f7cac8fb9ebebc15adc451180b

**Comment by Rinnegatamante** [comment]
They both have been fixed.
