### ISSUE TITLE
Typo in Settings - Camera "Sensibility" should be "Sensitivity"

### ISSUE THREAD

**Issue by Salvorite** [Rinnegatamante/vitaQuake#13]
Tested on version 2.0

**Comment by Rinnegatamante** [comment]
http://www.thesaurus.com/browse/sensibility

Shouldn't be the same? (Maybe in english they have different meanings, in italian the most accurated in this contest is sensibility)

**Comment by Ch0wW** [comment]
Sensitivity is actually the correct wording for it.

**Comment by Rinnegatamante** [comment]
Corrected.
