### ISSUE TITLE
Crashes with retail PAKs

### ISSUE THREAD

**Issue by PhonicUK** [Rinnegatamante/vitaQuake#2]
Steps to reproduce:
- Install vitaquake VPK via molecularShell
- Place PAK0.PAK and PAK1.PAK from current retail release (downloaded via Steam) in ux0:
- Start game

Results in a black screen. Pressing START results in:

```
An error has occurred in the following application.
(C2-12828-1)
```

**Comment by Rinnegatamante** [comment]
Theoretically when the black screen is showed, there should be some console debug lines talking about what error you got but there are a couple of bugs in current release apparently. When i'll get the PSTV i ordered on Amazon 2 days ago, i'll debug the whole homebrew and fix any bug i encounter. Thanks for the report.

**Comment by Rhodderz** [comment]
I dont think it is to do with the paks.
I have tried it with both retail and shareware packs and get the same result.

**Comment by Rinnegatamante** [comment]
Oh you placed the files in the wrong place apparently. pak files must be in ux0:/data/Quake/id1 like where pak0.pak is in the original v.1.3 release.

**Comment by PhonicUK** [comment]
Ah, in that case the instructions that have been doing the rounds are incorrect.

**Comment by Rinnegatamante** [comment]
From: http://wololo.net/talk/viewtopic.php?f=116&t=46185

Installation:
- Place the data folder in ux0:/
  
  If you want to use your full installation of Quake you just have to add pak1.pak file to data/Quake/id1 folder.
