### ISSUE TITLE
Crashes with full Quake PAK files

### ISSUE THREAD

**Issue by NeveHanter** [Rinnegatamante/vitaQuake#24]
Hey,

vitaQuake is crashing when starting new game or starting benchmark after I've replaced pak0.pak with full Quake pak0.pak file and put pak1.pak next to it.

Desktop clients like Darkplaces and Quakespasm run fine with these files.

Also when I put pak1.pak file inside ID1 without replacing pak0.pak it works to the moment when I select non-shareware episode, after that it crashes like with replaced pak0.pak.

**Comment by Ch0wW** [comment]
Using the latest official "release" of VitaQuake, I can't reproduce your problem at all, using several PAKx.PAK from my steam & gog release, aswell as my 1996 version.

By the way, PAK0.PAK is the only one shared between the shareware and the full game. You only need to transfer PAK1.PAK to unlock the full game.

Make sure your PAK files aren't corrupted or anything. Maybe it's on your end.

**Comment by NeveHanter** [comment]
Ok, I've tried with the GOG release of Quake and now it works without crashing.

Anyway it's quite weird that it didn't worked with my _working on PC_ files.
