### ISSUE TITLE
Starts into console instead of title screen

### ISSUE THREAD

**Issue by rsn8887** [Rinnegatamante/vitaQuake#25]
When I start the game, it doesn't go to the title menu. Instead it shows a console with the following messages:
EXECING QUAKE.RC
EXECING DEFAULT.CFG
"ALT" ISN'T A VALID KEY
"ENTER" ISN'T A VALID KEY
"ESCAPE" ISN"T A VALID KEY
UNKNOWN COMMAND "GAMMA"
EXECING CONFIG.CFG
COULDN'T EXEC AUTOEXEC.CFG
EXECING CONFIG.CFG
] {blinking cursor}

I have to press start to make the title menu show and then I can play.

**Comment by Ch0wW** [comment]
Those settings are used by the default configuration. It's normal it shows you this.

Quake does indeed starts to the Console, and not to the main menu. It should be a very quick improvement to do, and only one line to add from the startup logic. 

Problem is, I forgot how to recompile vitaQuake. So for now... I'm slightly stucked.

**Comment by Rinnegatamante** [comment]
vitaQuake on first releases was already starting up with demo1 reproduction (the one used for benchmark test too). It got erroneously changed with some commit later on. Looking into ctrQuake should be a first step to locate the change to perform.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/vitaQuake/commit/94558fd0272e6deb7993a4019ebdaa3e8901fc3b reintroduces demo playback at startup.
