### ISSUE TITLE
Dead Zones

### ISSUE THREAD

**Issue by cloudyd3** [Rinnegatamante/vitaQuake#3]
Can you add a dead zones for sticks?
Left stick on my Vita sometimes tilts right with out any reasons, I found its a popular problem.

**Comment by Rinnegatamante** [comment]
Yeah probably a good idea, when i'll receive my PSTV i'll start experimenting to find the most comfortable settings.

**Comment by Rinnegatamante** [comment]
Done with v.1.4.
