### ISSUE TITLE
Entities/Lightmaps clipping with world models

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/vitaQuake#31]
In some specific spots, moving parts of scenario are clipping with static world models causing a sort of texture flickering effect when moving camera.

Noticeable in Episode 1 Level 1 with the elevator that leads to the secret Quad damage.

**Comment by rsn8887** [comment]
The exact same thing happens with a fresh install of Fitzquake on Windows (E1L1 elevator shows the same "texture flickering" when moving camera)

**Comment by Rinnegatamante** [comment]
MMhhh that's an interesting discovery. Would be interesting to look into other source ports to see which one has actually fixed it.

**Comment by Rinnegatamante** [comment]
Referred to this bug:
This bug should be addressed with a patch like this:
http://forums.insideqc.com/viewtopic.php?f=12&t=1211&sid=96d9ecc7b3817de3298c9a2f9cb20e70

That specific one seems to not work, i suspect it's an issue in vitaGL rather than in the code itself.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaQuake/commit/0e3c36b0c2d0edff1308d66dd18c3682103e7cbe
