### ISSUE TITLE
Underwater gfx not displayed correctly.

### ISSUE THREAD

**Issue by ShroomKing** [Rinnegatamante/vitaQuake#32]

**Comment by ShroomKing** [comment]
Sorry, accidentally pressed enter and opened an issue without adding a description, i'll explain what i mean in a couple minutes + will add a couple screenshots

**Comment by ShroomKing** [comment]
So basically, when underwater everything get's pitch black and it's not really possible to see a thing aside from the water surface. first 2 screenshots are how it's supposed to look like and how it looked like on Software renderer vitaQuake

![2018-01-16-152149](https://user-images.githubusercontent.com/26014865/34995050-a8911c90-fad5-11e7-908a-66bc0c100ffa.jpg)

![2018-01-16-152156](https://user-images.githubusercontent.com/26014865/34995062-b0bea23e-fad5-11e7-9d5a-83db07fa978b.jpg)

and the following screenshots are how it currently looks like on vita-glQuake

![2018-01-16-151628](https://user-images.githubusercontent.com/26014865/34995101-d129c3e6-fad5-11e7-8344-e8e9e0d2693c.jpg)

![2018-01-16-154104](https://user-images.githubusercontent.com/26014865/34995133-e22d6d00-fad5-11e7-89a1-1438b632bfba.jpg)

![2018-01-16-153845](https://user-images.githubusercontent.com/26014865/34995139-e6b363ac-fad5-11e7-8008-bd074106badb.jpg)

![2018-01-16-151632](https://user-images.githubusercontent.com/26014865/34995152-edf86cb6-fad5-11e7-8666-d2d62d6134ea.jpg)

Also it seems like some particles are missing(Blood particles for example)

Other than that thanks for your work on this, the progress is impressive, and it rarely ever drops below 60fps(at max cpu/gpu/bus speeds)

**Comment by Rinnegatamante** [comment]
Do you have a screenshot from original glQuake? glQuake is well known to be a lot darker if compared to winQuake, i wouldn't be surprised if this is a glQuake "feature".

**Comment by ShroomKing** [comment]
This is how glQuake looks on my pc when underwater:

![unnamed40](https://user-images.githubusercontent.com/26014865/35002559-5477fa1a-faea-11e7-8559-bc1ceb639b23.png)

obviously i can see the floor/walls etc.  

on vita-glQuake there is no geometry AT ALL when underwater, everything is just black.

**Comment by Rinnegatamante** [comment]
Putting some reference here if someone wants to work on the issue:

The issue was not present before moving from vitaGL standard shaders to custom specialized shaders.
With that being said, the issue came out from https://github.com/Rinnegatamante/vitaQuake/commit/24e883897482d280c5055255083df883c39261ac this commit or a later one, surely not from a previous one.

**Comment by Rinnegatamante** [comment]
Issue is related to lightmaps. Using r_fullbright to disable lightmaps actually fixes the issue.

**Comment by Rinnegatamante** [comment]
The function causing this bug is DrawGLWaterPolyLightmap in gl_rsurf.

**Comment by Count-Duckula-AU** [comment]
Underwater looks great now with vitaquake v2.6. Everything is visible and the warping effect is present :)

**Comment by Rinnegatamante** [comment]
v.2.6 introduced a temporary fix that disables lightmaps. Issue is still here if underwater lightmaps are enabled like they should be.

**Comment by Count-Duckula-AU** [comment]
Thanks for the clarification.

**Comment by Rinnegatamante** [comment]
Solved, was a bug in vitaGL.
