### ISSUE TITLE
v2.6 crashing on start

### ISSUE THREAD

**Issue by karlos121** [Rinnegatamante/vitaQuake#34]
[vitaQuake Dumps.zip](https://github.com/Rinnegatamante/vitaQuake/files/1664142/vitaQuake.Dumps.zip)

Vita: PCH-1006
OS: 3.60 Henkaku

Installed over top of 2.5: Crashed after console messages finish scrolling
Deleted and reinstalled via Homebrew Browser, same issue. Rebooted in between uninstall and reinstall for good measure.

Not sure what else to add. Crash dumps attached.

**Comment by Rinnegatamante** [comment]
Do you have any official expansion installed?

**Comment by Rinnegatamante** [comment]
Should be solved now, redownload it from VitaDB.

**Comment by karlos121** [comment]
Tested and confirmed it's solved. Thank you and awesome work!
