### ISSUE TITLE
Implement "texture smoothing" option in menu

### ISSUE THREAD

**Issue by tiduscrying** [Rinnegatamante/vitaQuake#38]
The engine currently defaults to "gl_texturemode gl_linear" for the texture mode, however some people (myself included) like the crunchy look of "gl_texturemode gl_nearest". Maybe a quick toggle to choose between "linear" and "nearest" could be implemented in the options menu? I would try adding it to the menu.c file myself, but I don't know much about doing so and I wouldn't want to mess anything up...

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/vitaQuake/commit/2c50c6ae0eba686bf796aeb98ba05a1f83d58826
