### ISSUE TITLE
There aren't any instructions on how to build this.

### ISSUE THREAD

**Issue by Tutankhamun8080** [Rinnegatamante/vitaQuake#40]
If you could explain how to compile vitaQuake this would be helpful.
What programs to use? Cmake, Git & Visual Studio.
What files & commands to run?

**Comment by spacebruce** [comment]
Install the VitaSDK and set up building with the instructions here; https://vitasdk.org/
Install VitaGL (https://github.com/Rinnegatamante/vitaGl) with "make" then "make install"
Then just "make" in the vitaQuake directory should produce a working vitaquake.vpk

**Comment by Tutankhamun8080** [comment]
I greatly appreciate you. Thanks!
