### ISSUE TITLE
Small contribution

### ISSUE THREAD

**Issue by Ch3lin** [Rinnegatamante/vitaQuake#42]
I wanted to contribute with a minimal contribution in the exterior design of this great hombrew, who in the exterior icon is using the Quake 4 and inside is out of square. I'll try to do something better afterwards.
I hope they serve you and add it in your next release.

Thank you very much for your great work. Keep in that way

Preview:
https://ibb.co/cXUFbH
https://ibb.co/htDmix

Download:

https://mega.nz/#!YWpjRYhB!1POvbsECkKrDhMw_aqK9rzycqlL1lG8SRYd6FSzN5iU

**Comment by Rinnegatamante** [comment]
Thank you, introduced with https://github.com/Rinnegatamante/vitaQuake/commit/3ee364cafcadd8ec134b02ee889c9185d9abe4fb

**Comment by Ch3lin** [comment]
replace background for the complete work look the picture. :D
https://ibb.co/cXUFbH
https://mega.nz/#!YWpjRYhB!1POvbsECkKrDhMw_aqK9rzycqlL1lG8SRYd6FSzN5iU
