### ISSUE TITLE
Request - not an issue

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuake#46]
Sorry if this is posted in the wrong place, but I couldn't see where to do a request.

Currently Dopa and Abyss-Of-Pandemonium expansions seem to also work. I know I can strat these by bringing up the console and typing 'game impel' or 'game dopa' then start the game as normal. Would it be possible at some point to add a shortcut to the menu, or add a menu command so these can be selected from the main menu or vita icon screen?

Thanks.

**Comment by Rinnegatamante** [comment]
There is already a mod selector in options menu.
