### ISSUE TITLE
Add support for overbrights and fullbrights (Enhancement) (EDIT: Fullbrights are already done)

### ISSUE THREAD

**Issue by rsn8887** [Rinnegatamante/vitaQuake#47]
It would be extremely cool if Vitaquake could support both Overbrights and Fullbrights, which are used in Quake level data.

These are two features supported by vanilla software Quake and several Quake GL ports (Fitzquake and a few others), but not originally supported by vanilla GLQuake:

- **Overbrights**: This causes highlights to show up even in bright rooms (light value can go to 200%).

Overbrights off:
![overbright_sm139_spd_off](https://user-images.githubusercontent.com/13071547/73578042-4687ef00-4444-11ea-8ed4-53b9acb7ac82.jpg)

Overbrights on:
![overbright_sm139_spd_on](https://user-images.githubusercontent.com/13071547/73578059-50115700-4444-11ea-843f-b8cf5c7acc5f.jpg)

Overbrights off:
![overbright_start_off](https://user-images.githubusercontent.com/13071547/73578070-569fce80-4444-11ea-95ea-1d476b366e95.jpg)

Overbrights on:
![overbright_start_on](https://user-images.githubusercontent.com/13071547/73578081-5bfd1900-4444-11ea-86de-600882c70f8a.jpg)

- **Fullbrights:** some texture colors should appear at full brightness even in the shadow (switches, red arrows, lamps etc.)

fullbrights off:
![fullbrights_e1m1_off1](https://user-images.githubusercontent.com/13071547/73578088-628b9080-4444-11ea-825f-28d71dfceee2.png)

fullbrights on:
![fullbrights_e1m1_on1](https://user-images.githubusercontent.com/13071547/73578096-67504480-4444-11ea-980a-64cbf2b80fdc.png)

fullbrights off:
![fullbrights_start_off](https://user-images.githubusercontent.com/13071547/73578104-6cad8f00-4444-11ea-9f16-871eb8b284c2.png)

fullbrights on:
![fullbrights_start_on](https://user-images.githubusercontent.com/13071547/73578117-71724300-4444-11ea-93e1-d876126bdc3b.png)

(taken from https://www.quaddicted.com/engines/software_vs_glquake )

**Comment by Rinnegatamante** [comment]
If someone wants to work on this:
https://www.quakewiki.net/quakesrc/index.html
there's a fullbright tutorial here.
There's also an overbright one but it uses multitexturing that's not supported yet in vitaGL.

**Comment by rsn8887** [comment]
Thanks for the link. I followed the fullbright tutorial and made all the changes. 

I don't have my Vita to test it at the moment, but the finished source is on my fork in branch "fullbrights":

https://github.com/rsn8887/vitaQuake/tree/fullbrights

It compiles without errors, which is a good sign.

EDIT: It doesn't work by just blindly following the tutorial, the red arrows are now tinted. Might just be a small fix that's needed...

Note these fullbrights have nothing to do with the r_fullbright variable, which simply turns off all lighting on a map and makes everything extremely bright.

**Comment by rsn8887** [comment]
Fullbrights now work... will make PR.

**Comment by Rinnegatamante** [comment]
Overbright support added with https://github.com/Rinnegatamante/vitaQuake/commit/28d59da56d4f09eeafce619e7f15cf676f8a27c2
