### ISSUE TITLE
Could you compile a seperate build for me?

### ISSUE THREAD

**Issue by damteenagers** [Rinnegatamante/vitaQuake#5]
Okay, I have no idea how to compile this to ".VPK" format on windows for use with HENkaku.
Using ProQuake in VHBL is plain too slow. Whilst using vitaQuake 1.3 the performance is more or less the same.
So I was wondering whether you could create a separate build with the video resolution scaled down to 480x272 in vid_psp2.c and a reduced audio sample rate in snd_psp2.c.
If you could do that much would be appreciated.

**Comment by parkerlreed** [comment]
Commits from yesterday mention being able to play at PSP resolution. Will probably be in the next build (Nightly/weekly builds would be great)

**Comment by Zeroba** [comment]
Rinne has a lot of projects going at once. Nightly's may not happen but I could see a weekly build. All depends on Rinne really.

**Comment by Rinnegatamante** [comment]
A new release should came quite soon (i want to improve a bit sound before the release and maybe add also music support).

**Comment by damteenagers** [comment]
Thanks; hopefully this should be faster than proquake(PSP) at a reduced resolution.

**Comment by parkerlreed** [comment]
@Rinnegatamante Could you add your website URL to the readme? I was sitting here not realizing there was a new release until somebody mentioned the wololo forum post.
