### ISSUE TITLE
Make file - missing backslash

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuake#50]
On line 65 where you added the: source/gl_fullbright.o, you forgot to add the back slash to the line above, ie: it should be - source/gl_vidpsp2.o \

This results in the game not compiling, please can you add that. Thanks.

**Comment by rsn8887** [comment]
Thanks, it was my mistake. PR created https://github.com/Rinnegatamante/vitaQuake/pull/51

**Comment by mrdude2478** [comment]
Thanks rsn8887
