### ISSUE TITLE
Brightness adjustment to make game darker? [enhancement]

### ISSUE THREAD

**Issue by rsn8887** [Rinnegatamante/vitaQuake#54]
The brightness adjustment slider in VitaQuake can only make the game brighter, not darker, compared to default. 

Is it possible to make the game darker in general to make it more atmospheric? Maybe adjust the brightness slider range?

**Comment by Rinnegatamante** [comment]
brightness couldn't be changed in GLQuake.
Current implementation just prints a white rect with proper blend func in order to simulate it.

**Comment by rsn8887** [comment]
It might be possible to darken the image on the Vita using the same trick but with
glBlendFunc(GL_ZERO, GL_ONE_MINUS_SRC_ALPHA);
instead of
glBlendFunc(GL_DST_COLOR, GL_ONE_MINUS_SRC_ALPHA);

Not sure if it will look good, but I might try it and post some screenshots later.

**Comment by rsn8887** [comment]
It works with glBlendFunc(GL_ZERO, GL_SRC_ALPHA); it makes the game darker. But it doesn't look that great just looks like the screen brightness is reduced. 

I guess what is needed for better atmosphere is some kind of real dynamic range compression or enhancement of the color space to make darks regions and bright lights really pop.

**Comment by rsn8887** [comment]
The Vita GPU supports hardware gamma correction. It gives the effect I was looking for. In VitaGL.c, I replaced
```
gpu_alloc_texture(width, height, tex_format, data, tex);
```
with
```
gpu_alloc_texture(width, height, tex_format, data, tex);
sceGxmTextureSetGammaMode(&tex->gxm_tex, SCE_GXM_TEXTURE_GAMMA_BGR);
```
To enforce gamma correction for all textures.

Before gamma hack:
![](https://s13.postimg.org/9cqz5qzdj/after.jpg)

After gamma hack: 
![](https://s13.postimg.org/5dyd0jad3/Forced_Gamma.jpg)

The shadows are now really dark. At the same time, bright lights are still bright. I think this is more atmospheric and maybe closer to how it should look (compared to Software DOS Quake).

However it is a dirty global hack at the moment. It cannot be easily enabled or disabled, and the colors of overlays (menu, console and status bar) are obviously wrong.

**Comment by rsn8887** [comment]
For comparison, this is how Dosbox Quake using default gamma settings looks:
![](https://s13.postimg.org/3op9sis3r/dosbox_default.png)

I re-installed it in Dosbox myself to make sure gamma is at default.

It has an even more gritty-dark look.

**Comment by rsn8887** [comment]
For reference, a comprehensive article about gamma correction:
http://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/

**Comment by rsn8887** [comment]
Another example.

Before gamma hack:
![](https://s13.postimg.org/rtpza8k47/nogamma_2.jpg)

After gamma hack:
![](https://s13.postimg.org/4fhzy6rvb/gammahack_2.jpg)

Dosbox Quake default gamma:
![](https://s13.postimg.org/daiu8p8xz/dosbox_default_2.png)

**Comment by Rinnegatamante** [comment]
I don't get why you want to replicate GLQuake.

One of the biggest issues in GLQuake was the fact that everything looked dark as fuck when it shouldn't.
Everyone complained about it and every single source ports doesn't have that "dark as fuck" effect.

**Comment by rsn8887** [comment]
All I am saying is that it would be nice to have “gamma correction” as an option to turn on or off according to the user’s preference. I agree it is very dark. Most people will probably not make use of this setting. But some people (including me) might like it that way, because it is more true to the original vision of Quake.

**Comment by Rinnegatamante** [comment]
Original vision of Quake is software renderer (winQuake), not GLQuake.

**Comment by rsn8887** [comment]
No the original vision should be dosquake not winquake. winquake is already brighter than dosquake because of different (wrong) default gamma. So that’s what I am comparing with: software dosquake on dosbox with default settings. Also I was originally hoping for a more adjustable gamma value, but all I found was this on/off switch in the sdk.

Direct comparison with dosquake shows my gamma hack makes it slightly too dark. Just a tiny bit darker shadows than Dosquake.

**Comment by rsn8887** [comment]
I completely agree GLQuake should not be replicated. It wasn’t even official. My goal here is to give users the option to adjust gamma to make the game replicate the original dark shadows of software rendered dosquake a bit better. Original Dosquake was also “dark as fuck” but I liked it that way, at least for the single player campaign. It created a lot of atmosphere.

**Comment by Count-Duckula-AU** [comment]
Personally I quite like the darker look, I did play a LOT of GLQuake. Can fully understand if its not something you'd like to include though.

**Comment by Rinnegatamante** [comment]
This was already implemented in several versions ago. Will be adjustable even further with recent overbright support.
