### ISSUE TITLE
Mp3 playback from cd tracks.

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuake#55]
Currently ogg files work fine but mp3 in the cd tracks don't: 

Code error in: source/audiodec/cd_psp2.cpp

Line 186 needs changed:
from: FILE* fd = fopen(tmp,"rb"); 
to: fd = fopen(tmp,"rb");

Then both ogg and mp3 can work.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaQuake/commit/4dd491e3e691b858aa0d549bbf3a282948fb81ee

**Comment by mrdude2478** [comment]
Thanks for fixing.
