### ISSUE TITLE
Bringing vita from sleep with game open causes instability

### ISSUE THREAD

**Issue by Zeroba** [Rinnegatamante/vitaQuake#6]
When leaving the game open then sleeping the vita, the sound will sometimes begin to crackle and that's basically a sign the game became unstable. Finishing a level, saving, or doing a lot of things at that point will crash the game.
It also seems to affect Wolfenstein.
I can replicate and attach a dump, but I'm not sure if those dumps created by crashes actually help at all. I'm no dev. :)

**Comment by Rinnegatamante** [comment]
Take a coredump with this version (it has debug symbols so i can properly analyze the coredump file).
If it crashes at start (since it's based on latest version) create a folder in ux0:/data/Quake and name it cdtracks.
[vitaQuake.zip](https://github.com/Rinnegatamante/vitaQuake/files/414415/vitaQuake.zip)

**Comment by Zeroba** [comment]
Will do.

**Comment by Zeroba** [comment]
Weirdly enough, now rather than crashing with a dump, it's going straight back to the livearea when pressing save, not when trying to save or overwrite. If that makes any sense.
I'll keep messing with it and see if I can't get it to crash with a dump.

**Comment by Zeroba** [comment]
Tried for awhile, for some reason that version only quits to the live area instead of giving a dump.

**Comment by Rinnegatamante** [comment]
Pretty strange, anyway it seems suspending apps (i suppose sleep counts like a suspension) seems to produce strange behaviours on homebrews. I noticed a similar issue with EasyRPG Vita. Basically if you suspend EasyRPG when a BGM is playing, it will just crash cause the audio decoder will fail to read from BGM file for whatever reason (i suppose suspend closes i/o handles) and it will enter in a endless loop till it goes out of stack and produce a system crash.

Probably vitaQuake and vitaWolfen have similar issues with suspension/sleep.

**Comment by Zeroba** [comment]
Guess for the meantime I'll just be careful about sleeping it with the game open haha.

**Comment by rsn8887** [comment]
I think it is a known problem but not well documented. File I/O becomes unstable when returning from suspend. I am not sure if there is a solution yet. For UAE4All, the only workaround I found was to disable the PS button altogether.
