### ISSUE TITLE
Paths in makefile

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuake#60]
I see the makefile has been modded, however for some reason vpk's no longer pack correctly due to forward slash being changed for backslash in the paths.

Example:

This builds correctly
7z a -tzip ./$(TARGET).vpk -r ./build/sce_sys/* ./build/eboot.bin ./build/shaders/*

This doesn't
7z a -tzip ./$(TARGET).vpk -r .\build\sce_sys\* .\build\eboot.bin .\build\shaders\*

Also in linux (ubuntu), this needs changed from:
vita-make-fself -s $< build\eboot.bin

to

vita-make-fself -s $< build/eboot.bin

Or else the eboot file doesn't get put in the build directory - a file called buildeboot.bin gets created instead.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/vitaQuake/pull/59

**Comment by mrdude2478** [comment]
Dude, the makefile is broken now - I posted what's wrong, I saw the changes you made and read that post you re-directed me too, but the fact is that the makefile was working fine & now it's not (unless I edit it manually).

Thanks for your reply though, I appreciate you're busy and modding other code.
