### ISSUE TITLE
screen size / weapon height not setting correctly at start

### ISSUE THREAD

**Issue by Phoenix09** [Rinnegatamante/vitaQuake#62]
before restart:
![before restart](https://user-images.githubusercontent.com/3220224/36979096-59bf14fe-207e-11e8-8ecc-45e8fad00d63.jpg)

after restart:
slider in wrong place, weapon too low
![after restart](https://user-images.githubusercontent.com/3220224/36979095-59a5a168-207e-11e8-93fc-a8fa0c79d215.jpg)

changing screen size using `viewsize xxx` has no effect on weapon height which is likely why this happens

**Comment by Phoenix09** [comment]
`gl_fog ` has a similar problem
setting it in console will affect the state in options, but it won't have any effect on whether fog is shown or not

**Comment by Ch0wW** [comment]
Please check the Pull Request for the viewsize and weapon position error.
