### ISSUE TITLE
Live Area, icons and Background

### ISSUE THREAD

**Issue by Ch3lin** [Rinnegatamante/vitaQuake#64]
Improve the **background** and the icons of the expansions a little, I hope they serve you.
Preview:
![2018-03-13-222632](https://user-images.githubusercontent.com/36119214/37379185-2c0b1ece-2711-11e8-9826-633378dc4341.jpg)
![2018-03-13-222639](https://user-images.githubusercontent.com/36119214/37379186-2c2bdf92-2711-11e8-906c-ef317547fcdc.jpg)

Download:
https://mega.nz/#!lbQ1RKKZ!ATNpRjhZzkAMgugxJAHRvXOJwF3Kln_lnar_pqGCet4

**Comment by Rinnegatamante** [comment]
Added with https://github.com/Rinnegatamante/vitaQuake/commit/d3fe6320f7ac1a13d7e841dcc6a2f029ae6d6204
