### ISSUE TITLE
Graphics arent as good as unity.

### ISSUE THREAD

**Issue by SilicaAndPina** [Rinnegatamante/vitaQuake#65]
i read on IRC that quake engine is better than unity, but the graphics suck how to make them better

**Comment by Ch0wW** [comment]
... Are you serious.

**Comment by SilicaAndPina** [comment]
![dczrqnhuwaagkxw](https://user-images.githubusercontent.com/18594213/40928998-5b97cabe-6877-11e8-96b4-b01d9e25c6ca.png)

here rin says that quake is better than unity
