### ISSUE TITLE
vitaQuake online play

### ISSUE THREAD

**Issue by Lurgypai** [Rinnegatamante/vitaQuake#66]
I messed around a bit, and was able to connect to a few servers. But the quake screen never went up so I could see the game. Now I've never played quake, so I know very little about how online should work. I definitely connected, as I could see the chat, and was even killed once.

This could very easily be an error on my side, I'll do my best to troubleshoot if you have any advice.

**Comment by Rinnegatamante** [comment]
Do you have full game or just shareware files? If you have only shareware files and you join a server requiring full game it will make you impossible to really get inside the map since map autodownload doesn't properly work on PSVITA.

**Comment by Lurgypai** [comment]
That makes sense. I have only the data files that were available on vitaDB. Do I need to purchase the rest?

**Comment by Rinnegatamante** [comment]
If you're trying to join a server using original maps, yes.
