### ISSUE TITLE
Gives me error c2-12828-1 on startup.

### ISSUE THREAD

**Issue by Tomcoid** [Rinnegatamante/vitaQuake#68]
I've downloaded all 3 vitaquakes, and all 3 give me this error. Everything else on my vita works perfectly fine, so I don't think it's the console.

Henkaku enso 3.65, psvita slim with sd2vita

**Comment by Ch0wW** [comment]
I'm on 3.65 Enso, and I'm definitely not having this issue you're having.

Are you using the shareware version?

**Comment by Tomcoid** [comment]
I was dumb, didn't have the pak files
