### ISSUE TITLE
Swapping X(cross) and O(circle) for confirm screws up camera

### ISSUE THREAD

**Issue by Ilya69** [Rinnegatamante/vitaQuake#7]
If you decide to swap X and O from normal confirm (x) to Japaneese (o) it makes the camera go to the top right corner of the screen and it stays there. To replicate install Vita Quake 1.4 and Button swapper [Button Swapper](https://github.com/xyzz/vita-button-swapper/releases/tag/1.0) , swap to Japanese ,restart , apply Henkaku and launch the game.

**Comment by Rinnegatamante** [comment]
Are you sure the problem is connected with X/O swap? Aren't you pressing touchscreen or retrotouch?

**Comment by Ilya69** [comment]
i was touching the back touchscreen and getting VERY confused
