### ISSUE TITLE
no backround image and icons

### ISSUE THREAD

**Issue by smallpack** [Rinnegatamante/vitaQuake#71]
I have the problem that my Vita with your homebrews shows nothing as bubble even if I tap on the bubble is just a blank picture and then I can start

how do i get pictures in the empty fields?
I find nothing under ur: appmeta

I would like to use my pictures and change the Title id

i use the google translator -.-

**Comment by Rinnegatamante** [comment]
ux0:app/TITLEID (QUAK00001).
