### ISSUE TITLE
Adding ur0:/ support for "data" directory

### ISSUE THREAD

**Issue by kamilb880** [Rinnegatamante/vitaQuake#72]
It will be cool to have possibility to use ur0:/ partition as source for data directory - it takes most of the space that homebrew uses, and many users will be glad to have that option

**Comment by Rinnegatamante** [comment]
Same discussion as vitaQuakeII. uma0:/ support implemented with https://github.com/Rinnegatamante/vitaQuake/commit/94dfc3e7a742f561df01c580c465d513be0b0922
