### ISSUE TITLE
unable to compile now.

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuake#73]
I updated vitagl and vitasdk (via vdpm). Now for some reason I am unable to compile this now. I went to older versions of vitasdk + vitagl and still got errors, so I reinstalled mysys2 and all the required stuff + vitasdk and vitagl. Each time I try and build I get the following errors:

c:/msys32/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/8.2.0/../../../../arm-vita-eabi/bin/ld.exe: C:\msys32\tmp\ccigDhpAd                        ebugobjtem: file not recognized: file truncated
collect2.exe: error: ld returned 1 exit status
lto-wrapper.exe: fatal error: C:\msys32\usr\local\vitasdk\bin\arm-vita-eabi-g++.exe returned 1 exit status
compilation terminated.
c:/msys32/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/8.2.0/../../../../arm-vita-eabi/bin/ld.exe: error: lto-wrapper fail                        ed
collect2.exe: error: ld returned 1 exit status

LTO-wrapper fails because the files are truncated, what would cause this, even after a fresh install of everything? (same errors as before reinstalling).

**Comment by Rinnegatamante** [comment]
Disable fto (-fno-lto CFLAG) and reorder libraries accordingly.

**Comment by mrdude2478** [comment]
I ended up compiling in linux (ubuntu) instead and it compiled fine, it wouldn't compile in mysys2 on windows though, no matter what I tried - even with a fresh install. I've no idea what caused the problem - but I'm playing now so thanks.
