### ISSUE TITLE
4.0 Crashes on startup

### ISSUE THREAD

**Issue by noradninja** [Rinnegatamante/vitaQuake#75]
Log file says:
`W_LoadWadFile: couldn't load gfx.wad`
This is using files from the previously working version, tried erasing and reloading them, same issue.

**Comment by Rinnegatamante** [comment]
Are your files from Shareware version of Full version? If full, are they coming from Steam, GOG or official CD?

**Comment by noradninja** [comment]
Full version, original CD.

**Comment by Rinnegatamante** [comment]
I'm with Steam version and i don't get this error. Do you have gfx.wad somewhere in your id1 folder/subfolders?

**Comment by noradninja** [comment]
No, never have, and it’s always worked with older versions of VitaQuake.

**Comment by Rinnegatamante** [comment]
Kinda strange, never had this issue with Steam data files. I can send you gfx.wad from my Steam data files (you would need to replace it in pak0.pak with a pak editor like PakExplorer. You can also replace said gfx.wad with the one from pak0.pak from shareware files included with vitaQuake.

**Comment by noradninja** [comment]
Sounds good, would you mind?

**Comment by Rinnegatamante** [comment]
[gfx.zip](https://github.com/Rinnegatamante/vitaQuake/files/3641671/gfx.zip)

**Comment by XvladwolfmanX** [comment]
I have the same issue with GOG version of the game. I've tryed to replace gfx.wad but error is the same `W_LoadWadFile: couldn't load gfx.wad`.

**Comment by Rinnegatamante** [comment]
You have to replace it inside your pak file.

Il giorno mar 24 set 2019 alle ore 08:46 XvladwolfmanX <
notifications@github.com> ha scritto:

**Comment by XvladwolfmanX** [comment]
Yes, I replaced it inside the pak0 file with PakExplorer.

**Comment by Rinnegatamante** [comment]
Are your pakfiles/folders all lowercased? (Extension too)

**Comment by XvladwolfmanX** [comment]
Folders all lowercased, but pak files not (LIGHTS.PAK, PAK0.PAK, PAK1.PAK). In previous version all was worked fine.

**Comment by XvladwolfmanX** [comment]
Yeah, I've just renamed the files to lowercase and the game now launches fine. With NOTmodified pak0.pak file works too.

**Comment by Rinnegatamante** [comment]
I think i know what caused uppercases paks to not be detected anymore. If so, i'll fix it in next release however for the meantime, lowercases will do the trick.

**Comment by noradninja** [comment]
![C809E5FC-D000-45C6-B440-248894BBE38B](https://user-images.githubusercontent.com/6692990/66271213-73771d00-e829-11e9-9ab8-3ab8952dd616.jpeg)
After fixing the case issue, I can now start the game, and load my save file for The Wind Tunnels, but if I start a new game this is eventually what happens.

**Comment by noradninja** [comment]
So this is due to my external .lit files for colored lighting, which is broken in this release. Removing them fixes the loading issue.
