### ISSUE TITLE
4.0 no longer supports external .lit files

### ISSUE THREAD

**Issue by noradninja** [Rinnegatamante/vitaQuake#78]
Using the same .lit package as the previous version, this version no longer loads most maps, eg the Start map among others. See .lit package at [The Quake Wiki](www.quaketastic.com/files/misc/litvis_packs/id1_litvis.zip)

**Comment by Rinnegatamante** [comment]
Is this still the case in 4.1?

**Comment by noradninja** [comment]
The latest version of the app actually launches to a black screen then crashes back to LA. This is with or without .lit files in place on my 3.65 Ensō modded 1000.

**Comment by Rinnegatamante** [comment]
Something's clairly broken on your side.
Disable all plugins and check if you have remaining data files in uma0.

**Comment by noradninja** [comment]
Did have data in uma0. Launches now to console, but crashes, log says 'Ran out of virtual texture space. 1572864'. I am using High res textures from QRP, extracted to /data/quake/id1/textures (170.1MB total) and /data/quake/id1/progs  (70.1MB total). I have gl_compress set to 1 in auto exec.cfg (although the behavior is the same without it in there). In the previous version, I didn't have that in the config, and the textures loaded fine, just took about 40 seconds to load a map.

**Comment by noradninja** [comment]
I downscaled the textures by 50% (no visual difference so that is fine). I had to disable the cache with -no_tex_cache in the boot args to get the game to launch correctly with external texture files, which now total 69.6MB. The external .lit files now work correctly again. Thanks for the help.

**Comment by Rinnegatamante** [comment]
Texture cache got re-enabled by default cause was seemingly the cause of tons of gpu crashes.

**Comment by noradninja** [comment]
Understood. At this point the .lit files are working fine, so this particular issue is closed as far as I am concerned. Is it possible you could add a graphics option for the cache arg for people like me that use it for external textures so I don't have to input it every time?

**Comment by Rinnegatamante** [comment]
You can create a bat file and launch it with the custom args more easily ("-bat a" to launch a.bat)

**Comment by noradninja** [comment]
Thanks.
