### ISSUE TITLE
Settings are not persistent

### ISSUE THREAD

**Issue by lincruste** [Rinnegatamante/vitaQuake#8]
Hi, thank you for this Quake port, probably the best handheld version thanks to your dual analog nubs support.

I encounter an issue, however, as settings seems to be non-persistent (inverted cam, screen brightness, always run on, etc), just like if some config file could not be written/modified.
When VitaQuake is stopped and executed again, I have to set it all back.

Tested on a "fat" 3G Ps Vita with the latest Henkaku homebrew enabler.

Sorry for my english.

**Comment by Rinnegatamante** [comment]
Some config values are not saved cause they're not normal config but "hacky" config.

**Comment by lincruste** [comment]
Hi, 
Even features found in the original WinQuake like "always run", "brightness" or "invert camera" ?
What I mean is I did not manage to get a single setting to be saved (but save files do work).

**Comment by Rinnegatamante** [comment]
Now solved for both standard and new settings. Will be available in v.1.5.

**Comment by lincruste** [comment]
Thanks a lot for your work on this. 
Regards
