### ISSUE TITLE
Crashes when sleeping and entering and leaving the LiveArea

### ISSUE THREAD

**Issue by resero971** [Rinnegatamante/vitaQuake#85]
Basically the title. Whenever I put my my Vita into sleep mode or I leave the game, I get 'error C2-12828-1'.

I don't use sd2vita and my vita is running enso 3.60. I'm running vitaQuake 4.1 (according to the start up screen), no mods other than the official expansions and ost. I didn't have this issue until recently. No other games have/had this issue, even before I downgraded.

If this has already been solved or is already a known issue please let me know or point me in the right direction.

**Comment by Ch0wW** [comment]
It's sadly a common issue with homebrews for the PSVita that cannot be fixed until we know how.
Whenever you go back to the home menu or put your console to sleep, the homebrew will have issues with loading/opening/writing files until you restart the homebrew.

**Comment by resero971** [comment]
Ok Thank You For Your Time

**Comment by Rinnegatamante** [comment]
If you install FdFix, you won't have this issue: https://github.com/TheOfficialFloW/FdFix
Hopefully one day this will be integrated in taihen (maybe with henlo release)
