### ISSUE TITLE
crash on a specific room

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/vitaQuake#89]
On hipnotic/Scourge of Armageddon.

I have the DMP and Save file.

There a room with lots of Lightning ⚡⚡ strikes going on when I open the door

**Comment by Sarkie** [comment]
https://drive.google.com/file/d/14XDsFjvOYPm8M9EJUkvck6c9vU01uAEh/view?usp=drivesdk

https://drive.google.com/file/d/14WxVFISr729XwtOBhz4R2QEIh1Sk3jul/view?usp=drivesdk

**Comment by Rinnegatamante** [comment]
vitaQuake is discontinued. No further updates will be pushed for it.

**Comment by Sarkie** [comment]
Thanks @Rinnegatamante 
For anyone else, Quakespasm loads the same .sav files, so it's easy to carry on.
Cheers!
